module BattleNetClient
  class Client
    BATTLE_NET_BASE_URL: String
    BATTLE_NET_OAUTH_URL: String
    BATTLE_NET_OAUTH_PAYLOAD: String
    BATTLE_NET_USER_INFO_URL: String
    DEFAULT_LOCALE: String

    include WorldOfWarcraft

    def access_token: () -> String | () -> nil
    def config: () -> ::ActiveSupport::Configuration
  end
end
