version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rake test
          command: bundle exec rake
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: 'echo "Skipping"'
workflows:
  build-and-test:
    jobs:
      - test-ruby